"""baseline

Revision ID: 4b256f9ea6f3
Revises: 
Create Date: 2025-11-03 12:29:54.240280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b256f9ea6f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loyalty_accounts', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='loyalty')
    op.alter_column('loyalty_accounts', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='loyalty')
    op.alter_column('loyalty_accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='loyalty')
    op.alter_column('loyalty_accounts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='loyalty')
    op.drop_index(op.f('idx_loyalty_accounts_tier'), table_name='loyalty_accounts', schema='loyalty')
    op.drop_index(op.f('idx_loyalty_accounts_user_id'), table_name='loyalty_accounts', schema='loyalty')
    op.drop_constraint(op.f('loyalty_accounts_user_id_key'), 'loyalty_accounts', schema='loyalty', type_='unique')
    op.create_index(op.f('ix_loyalty_loyalty_accounts_user_id'), 'loyalty_accounts', ['user_id'], unique=True, schema='loyalty')
    op.add_column('loyalty_redemptions', sa.Column('is_consumed', sa.Boolean(), nullable=False), schema='loyalty')
    op.add_column('loyalty_redemptions', sa.Column('validated_at', sa.TIMESTAMP(timezone=True), nullable=True), schema='loyalty')
    op.add_column('loyalty_redemptions', sa.Column('validated_by_provider_id', sa.String(), nullable=True), schema='loyalty')
    op.add_column('loyalty_redemptions', sa.Column('settlement_status', sa.String(length=20), nullable=False), schema='loyalty')
    op.add_column('loyalty_redemptions', sa.Column('settlement_provider_amount', sa.Integer(), nullable=True), schema='loyalty')
    op.add_column('loyalty_redemptions', sa.Column('settlement_platform_amount', sa.Integer(), nullable=True), schema='loyalty')
    op.alter_column('loyalty_redemptions', 'reward_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               schema='loyalty')
    op.alter_column('loyalty_redemptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='loyalty')
    op.alter_column('loyalty_redemptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='loyalty')
    op.drop_index(op.f('idx_redemptions_account'), table_name='loyalty_redemptions', schema='loyalty')
    op.drop_index(op.f('idx_redemptions_created'), table_name='loyalty_redemptions', schema='loyalty')
    op.drop_index(op.f('idx_redemptions_reward'), table_name='loyalty_redemptions', schema='loyalty')
    op.drop_index(op.f('idx_redemptions_status'), table_name='loyalty_redemptions', schema='loyalty')
    op.drop_index(op.f('idx_redemptions_voucher_code'), table_name='loyalty_redemptions', schema='loyalty')
    op.drop_constraint(op.f('loyalty_redemptions_voucher_code_key'), 'loyalty_redemptions', schema='loyalty', type_='unique')
    op.create_index(op.f('ix_loyalty_loyalty_redemptions_account_id'), 'loyalty_redemptions', ['account_id'], unique=False, schema='loyalty')
    op.create_index(op.f('ix_loyalty_loyalty_redemptions_created_at'), 'loyalty_redemptions', ['created_at'], unique=False, schema='loyalty')
    op.create_index(op.f('ix_loyalty_loyalty_redemptions_is_consumed'), 'loyalty_redemptions', ['is_consumed'], unique=False, schema='loyalty')
    op.create_index(op.f('ix_loyalty_loyalty_redemptions_reward_id'), 'loyalty_redemptions', ['reward_id'], unique=False, schema='loyalty')
    op.create_index(op.f('ix_loyalty_loyalty_redemptions_validated_by_provider_id'), 'loyalty_redemptions', ['validated_by_provider_id'], unique=False, schema='loyalty')
    op.create_index(op.f('ix_loyalty_loyalty_redemptions_voucher_code'), 'loyalty_redemptions', ['voucher_code'], unique=True, schema='loyalty')
    op.drop_constraint(op.f('loyalty_redemptions_account_id_fkey'), 'loyalty_redemptions', schema='loyalty', type_='foreignkey')
    op.create_foreign_key(None, 'loyalty_redemptions', 'loyalty_accounts', ['account_id'], ['id'], source_schema='loyalty', referent_schema='loyalty')
    op.alter_column('loyalty_rules', 'tier_multipliers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               schema='loyalty')
    op.alter_column('loyalty_rules', 'conditions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               schema='loyalty')
    op.alter_column('loyalty_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='loyalty')
    op.alter_column('loyalty_rules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='loyalty')
    op.drop_index(op.f('idx_loyalty_rules_active'), table_name='loyalty_rules', schema='loyalty')
    op.drop_index(op.f('idx_loyalty_rules_priority'), table_name='loyalty_rules', schema='loyalty')
    op.drop_index(op.f('idx_loyalty_rules_provider'), table_name='loyalty_rules', schema='loyalty')
    op.drop_index(op.f('idx_loyalty_rules_provider_category'), table_name='loyalty_rules', schema='loyalty')
    op.drop_index(op.f('idx_loyalty_rules_service'), table_name='loyalty_rules', schema='loyalty')
    op.drop_index(op.f('idx_loyalty_rules_service_category'), table_name='loyalty_rules', schema='loyalty')
    op.create_index(op.f('ix_loyalty_loyalty_rules_provider_category_id'), 'loyalty_rules', ['provider_category_id'], unique=False, schema='loyalty')
    op.create_index(op.f('ix_loyalty_loyalty_rules_provider_id'), 'loyalty_rules', ['provider_id'], unique=False, schema='loyalty')
    op.create_index(op.f('ix_loyalty_loyalty_rules_service_category_id'), 'loyalty_rules', ['service_category_id'], unique=False, schema='loyalty')
    op.create_index(op.f('ix_loyalty_loyalty_rules_service_id'), 'loyalty_rules', ['service_id'], unique=False, schema='loyalty')
    op.alter_column('loyalty_transactions', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               schema='loyalty')
    op.alter_column('loyalty_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='loyalty')
    op.drop_index(op.f('idx_loyalty_transactions_account_id'), table_name='loyalty_transactions', schema='loyalty')
    op.drop_index(op.f('idx_loyalty_transactions_created'), table_name='loyalty_transactions', schema='loyalty')
    op.drop_index(op.f('idx_loyalty_transactions_expired'), table_name='loyalty_transactions', schema='loyalty')
    op.drop_index(op.f('idx_loyalty_transactions_expires'), table_name='loyalty_transactions', schema='loyalty')
    op.drop_index(op.f('idx_loyalty_transactions_idempotency'), table_name='loyalty_transactions', schema='loyalty')
    op.drop_index(op.f('idx_loyalty_transactions_provider'), table_name='loyalty_transactions', schema='loyalty')
    op.drop_index(op.f('idx_loyalty_transactions_reference'), table_name='loyalty_transactions', schema='loyalty')
    op.drop_index(op.f('idx_loyalty_transactions_type'), table_name='loyalty_transactions', schema='loyalty')
    op.drop_constraint(op.f('loyalty_transactions_idempotency_key_key'), 'loyalty_transactions', schema='loyalty', type_='unique')
    op.create_index(op.f('ix_loyalty_loyalty_transactions_account_id'), 'loyalty_transactions', ['account_id'], unique=False, schema='loyalty')
    op.create_index(op.f('ix_loyalty_loyalty_transactions_created_at'), 'loyalty_transactions', ['created_at'], unique=False, schema='loyalty')
    op.create_index(op.f('ix_loyalty_loyalty_transactions_expires_at'), 'loyalty_transactions', ['expires_at'], unique=False, schema='loyalty')
    op.create_index(op.f('ix_loyalty_loyalty_transactions_idempotency_key'), 'loyalty_transactions', ['idempotency_key'], unique=True, schema='loyalty')
    op.create_index(op.f('ix_loyalty_loyalty_transactions_is_expired'), 'loyalty_transactions', ['is_expired'], unique=False, schema='loyalty')
    op.create_index(op.f('ix_loyalty_loyalty_transactions_provider_id'), 'loyalty_transactions', ['provider_id'], unique=False, schema='loyalty')
    op.create_index(op.f('ix_loyalty_loyalty_transactions_reference_id'), 'loyalty_transactions', ['reference_id'], unique=False, schema='loyalty')
    op.create_index(op.f('ix_loyalty_loyalty_transactions_reference_type'), 'loyalty_transactions', ['reference_type'], unique=False, schema='loyalty')
    op.create_index(op.f('ix_loyalty_loyalty_transactions_transaction_type'), 'loyalty_transactions', ['transaction_type'], unique=False, schema='loyalty')
    op.drop_constraint(op.f('loyalty_transactions_account_id_fkey'), 'loyalty_transactions', schema='loyalty', type_='foreignkey')
    op.create_foreign_key(None, 'loyalty_transactions', 'loyalty_accounts', ['account_id'], ['id'], source_schema='loyalty', referent_schema='loyalty')
    op.alter_column('provider_loyalty_configs', 'is_participating',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether provider has opted into the loyalty program',
               existing_nullable=False,
               existing_server_default=sa.text('false'),
               schema='loyalty')
    op.alter_column('provider_loyalty_configs', 'point_multiplier',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='Multiplier for points awarded (1.0x, 1.5x, 2.0x, etc.)',
               existing_nullable=False,
               existing_server_default=sa.text('1.0'),
               schema='loyalty')
    op.alter_column('provider_loyalty_configs', 'participation_tier',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Tier level: basic, premium, elite',
               existing_nullable=True,
               schema='loyalty')
    op.alter_column('provider_loyalty_configs', 'billing_plan',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Billing model: free, pay_per_point, monthly_subscription',
               existing_nullable=False,
               existing_server_default=sa.text("'free'::character varying"),
               schema='loyalty')
    op.alter_column('provider_loyalty_configs', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               schema='loyalty')
    op.alter_column('provider_loyalty_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='loyalty')
    op.alter_column('provider_loyalty_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='loyalty')
    op.drop_index(op.f('idx_provider_loyalty_configs_billing'), table_name='provider_loyalty_configs', schema='loyalty')
    op.drop_index(op.f('idx_provider_loyalty_configs_participating'), table_name='provider_loyalty_configs', schema='loyalty')
    op.drop_index(op.f('idx_provider_loyalty_configs_tier'), table_name='provider_loyalty_configs', schema='loyalty')
    op.create_index(op.f('ix_loyalty_provider_loyalty_configs_is_participating'), 'provider_loyalty_configs', ['is_participating'], unique=False, schema='loyalty')
    op.create_index(op.f('ix_loyalty_provider_loyalty_configs_participation_tier'), 'provider_loyalty_configs', ['participation_tier'], unique=False, schema='loyalty')
    op.create_index(op.f('ix_loyalty_provider_loyalty_configs_provider_id'), 'provider_loyalty_configs', ['provider_id'], unique=False, schema='loyalty')
    op.drop_table_comment(
        'provider_loyalty_configs',
        existing_comment='Tracks provider participation in loyalty program',
        schema='loyalty'
    )
    op.alter_column('rewards', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               schema='loyalty')
    op.alter_column('rewards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='loyalty')
    op.alter_column('rewards', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='loyalty')
    op.drop_index(op.f('idx_rewards_active'), table_name='rewards', schema='loyalty')
    op.drop_index(op.f('idx_rewards_points_cost'), table_name='rewards', schema='loyalty')
    op.drop_index(op.f('idx_rewards_tier'), table_name='rewards', schema='loyalty')
    op.drop_index(op.f('idx_rewards_type'), table_name='rewards', schema='loyalty')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_rewards_type'), 'rewards', ['reward_type'], unique=False, schema='loyalty')
    op.create_index(op.f('idx_rewards_tier'), 'rewards', ['min_tier_required'], unique=False, schema='loyalty')
    op.create_index(op.f('idx_rewards_points_cost'), 'rewards', ['points_cost'], unique=False, schema='loyalty')
    op.create_index(op.f('idx_rewards_active'), 'rewards', ['is_active'], unique=False, schema='loyalty')
    op.alter_column('rewards', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='loyalty')
    op.alter_column('rewards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='loyalty')
    op.alter_column('rewards', 'extra_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='loyalty')
    op.create_table_comment(
        'provider_loyalty_configs',
        'Tracks provider participation in loyalty program',
        existing_comment=None,
        schema='loyalty'
    )
    op.drop_index(op.f('ix_loyalty_provider_loyalty_configs_provider_id'), table_name='provider_loyalty_configs', schema='loyalty')
    op.drop_index(op.f('ix_loyalty_provider_loyalty_configs_participation_tier'), table_name='provider_loyalty_configs', schema='loyalty')
    op.drop_index(op.f('ix_loyalty_provider_loyalty_configs_is_participating'), table_name='provider_loyalty_configs', schema='loyalty')
    op.create_index(op.f('idx_provider_loyalty_configs_tier'), 'provider_loyalty_configs', ['participation_tier'], unique=False, schema='loyalty')
    op.create_index(op.f('idx_provider_loyalty_configs_participating'), 'provider_loyalty_configs', ['is_participating'], unique=False, schema='loyalty')
    op.create_index(op.f('idx_provider_loyalty_configs_billing'), 'provider_loyalty_configs', ['billing_plan'], unique=False, schema='loyalty')
    op.alter_column('provider_loyalty_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='loyalty')
    op.alter_column('provider_loyalty_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='loyalty')
    op.alter_column('provider_loyalty_configs', 'extra_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='loyalty')
    op.alter_column('provider_loyalty_configs', 'billing_plan',
               existing_type=sa.VARCHAR(length=50),
               comment='Billing model: free, pay_per_point, monthly_subscription',
               existing_nullable=False,
               existing_server_default=sa.text("'free'::character varying"),
               schema='loyalty')
    op.alter_column('provider_loyalty_configs', 'participation_tier',
               existing_type=sa.VARCHAR(length=20),
               comment='Tier level: basic, premium, elite',
               existing_nullable=True,
               schema='loyalty')
    op.alter_column('provider_loyalty_configs', 'point_multiplier',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Multiplier for points awarded (1.0x, 1.5x, 2.0x, etc.)',
               existing_nullable=False,
               existing_server_default=sa.text('1.0'),
               schema='loyalty')
    op.alter_column('provider_loyalty_configs', 'is_participating',
               existing_type=sa.BOOLEAN(),
               comment='Whether provider has opted into the loyalty program',
               existing_nullable=False,
               existing_server_default=sa.text('false'),
               schema='loyalty')
    op.drop_constraint(None, 'loyalty_transactions', schema='loyalty', type_='foreignkey')
    op.create_foreign_key(op.f('loyalty_transactions_account_id_fkey'), 'loyalty_transactions', 'loyalty_accounts', ['account_id'], ['id'], source_schema='loyalty', referent_schema='loyalty', ondelete='CASCADE')
    op.drop_index(op.f('ix_loyalty_loyalty_transactions_transaction_type'), table_name='loyalty_transactions', schema='loyalty')
    op.drop_index(op.f('ix_loyalty_loyalty_transactions_reference_type'), table_name='loyalty_transactions', schema='loyalty')
    op.drop_index(op.f('ix_loyalty_loyalty_transactions_reference_id'), table_name='loyalty_transactions', schema='loyalty')
    op.drop_index(op.f('ix_loyalty_loyalty_transactions_provider_id'), table_name='loyalty_transactions', schema='loyalty')
    op.drop_index(op.f('ix_loyalty_loyalty_transactions_is_expired'), table_name='loyalty_transactions', schema='loyalty')
    op.drop_index(op.f('ix_loyalty_loyalty_transactions_idempotency_key'), table_name='loyalty_transactions', schema='loyalty')
    op.drop_index(op.f('ix_loyalty_loyalty_transactions_expires_at'), table_name='loyalty_transactions', schema='loyalty')
    op.drop_index(op.f('ix_loyalty_loyalty_transactions_created_at'), table_name='loyalty_transactions', schema='loyalty')
    op.drop_index(op.f('ix_loyalty_loyalty_transactions_account_id'), table_name='loyalty_transactions', schema='loyalty')
    op.create_unique_constraint(op.f('loyalty_transactions_idempotency_key_key'), 'loyalty_transactions', ['idempotency_key'], schema='loyalty')
    op.create_index(op.f('idx_loyalty_transactions_type'), 'loyalty_transactions', ['transaction_type'], unique=False, schema='loyalty')
    op.create_index(op.f('idx_loyalty_transactions_reference'), 'loyalty_transactions', ['reference_type', 'reference_id'], unique=False, schema='loyalty')
    op.create_index(op.f('idx_loyalty_transactions_provider'), 'loyalty_transactions', ['provider_id'], unique=False, schema='loyalty')
    op.create_index(op.f('idx_loyalty_transactions_idempotency'), 'loyalty_transactions', ['idempotency_key'], unique=False, schema='loyalty')
    op.create_index(op.f('idx_loyalty_transactions_expires'), 'loyalty_transactions', ['expires_at'], unique=False, schema='loyalty')
    op.create_index(op.f('idx_loyalty_transactions_expired'), 'loyalty_transactions', ['is_expired'], unique=False, schema='loyalty')
    op.create_index(op.f('idx_loyalty_transactions_created'), 'loyalty_transactions', ['created_at'], unique=False, schema='loyalty')
    op.create_index(op.f('idx_loyalty_transactions_account_id'), 'loyalty_transactions', ['account_id'], unique=False, schema='loyalty')
    op.alter_column('loyalty_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='loyalty')
    op.alter_column('loyalty_transactions', 'extra_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='loyalty')
    op.drop_index(op.f('ix_loyalty_loyalty_rules_service_id'), table_name='loyalty_rules', schema='loyalty')
    op.drop_index(op.f('ix_loyalty_loyalty_rules_service_category_id'), table_name='loyalty_rules', schema='loyalty')
    op.drop_index(op.f('ix_loyalty_loyalty_rules_provider_id'), table_name='loyalty_rules', schema='loyalty')
    op.drop_index(op.f('ix_loyalty_loyalty_rules_provider_category_id'), table_name='loyalty_rules', schema='loyalty')
    op.create_index(op.f('idx_loyalty_rules_service_category'), 'loyalty_rules', ['service_category_id'], unique=False, schema='loyalty')
    op.create_index(op.f('idx_loyalty_rules_service'), 'loyalty_rules', ['service_id'], unique=False, schema='loyalty')
    op.create_index(op.f('idx_loyalty_rules_provider_category'), 'loyalty_rules', ['provider_category_id'], unique=False, schema='loyalty')
    op.create_index(op.f('idx_loyalty_rules_provider'), 'loyalty_rules', ['provider_id'], unique=False, schema='loyalty')
    op.create_index(op.f('idx_loyalty_rules_priority'), 'loyalty_rules', [sa.literal_column('priority DESC')], unique=False, schema='loyalty')
    op.create_index(op.f('idx_loyalty_rules_active'), 'loyalty_rules', ['is_active'], unique=False, schema='loyalty')
    op.alter_column('loyalty_rules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='loyalty')
    op.alter_column('loyalty_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='loyalty')
    op.alter_column('loyalty_rules', 'conditions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='loyalty')
    op.alter_column('loyalty_rules', 'tier_multipliers',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='loyalty')
    op.drop_constraint(None, 'loyalty_redemptions', schema='loyalty', type_='foreignkey')
    op.create_foreign_key(op.f('loyalty_redemptions_account_id_fkey'), 'loyalty_redemptions', 'loyalty_accounts', ['account_id'], ['id'], source_schema='loyalty', referent_schema='loyalty', ondelete='CASCADE')
    op.drop_index(op.f('ix_loyalty_loyalty_redemptions_voucher_code'), table_name='loyalty_redemptions', schema='loyalty')
    op.drop_index(op.f('ix_loyalty_loyalty_redemptions_validated_by_provider_id'), table_name='loyalty_redemptions', schema='loyalty')
    op.drop_index(op.f('ix_loyalty_loyalty_redemptions_reward_id'), table_name='loyalty_redemptions', schema='loyalty')
    op.drop_index(op.f('ix_loyalty_loyalty_redemptions_is_consumed'), table_name='loyalty_redemptions', schema='loyalty')
    op.drop_index(op.f('ix_loyalty_loyalty_redemptions_created_at'), table_name='loyalty_redemptions', schema='loyalty')
    op.drop_index(op.f('ix_loyalty_loyalty_redemptions_account_id'), table_name='loyalty_redemptions', schema='loyalty')
    op.create_unique_constraint(op.f('loyalty_redemptions_voucher_code_key'), 'loyalty_redemptions', ['voucher_code'], schema='loyalty')
    op.create_index(op.f('idx_redemptions_voucher_code'), 'loyalty_redemptions', ['voucher_code'], unique=False, schema='loyalty')
    op.create_index(op.f('idx_redemptions_status'), 'loyalty_redemptions', ['status'], unique=False, schema='loyalty')
    op.create_index(op.f('idx_redemptions_reward'), 'loyalty_redemptions', ['reward_id'], unique=False, schema='loyalty')
    op.create_index(op.f('idx_redemptions_created'), 'loyalty_redemptions', ['created_at'], unique=False, schema='loyalty')
    op.create_index(op.f('idx_redemptions_account'), 'loyalty_redemptions', ['account_id'], unique=False, schema='loyalty')
    op.alter_column('loyalty_redemptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='loyalty')
    op.alter_column('loyalty_redemptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='loyalty')
    op.alter_column('loyalty_redemptions', 'reward_value',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='loyalty')
    op.drop_column('loyalty_redemptions', 'settlement_platform_amount', schema='loyalty')
    op.drop_column('loyalty_redemptions', 'settlement_provider_amount', schema='loyalty')
    op.drop_column('loyalty_redemptions', 'settlement_status', schema='loyalty')
    op.drop_column('loyalty_redemptions', 'validated_by_provider_id', schema='loyalty')
    op.drop_column('loyalty_redemptions', 'validated_at', schema='loyalty')
    op.drop_column('loyalty_redemptions', 'is_consumed', schema='loyalty')
    op.drop_index(op.f('ix_loyalty_loyalty_accounts_user_id'), table_name='loyalty_accounts', schema='loyalty')
    op.create_unique_constraint(op.f('loyalty_accounts_user_id_key'), 'loyalty_accounts', ['user_id'], schema='loyalty')
    op.create_index(op.f('idx_loyalty_accounts_user_id'), 'loyalty_accounts', ['user_id'], unique=False, schema='loyalty')
    op.create_index(op.f('idx_loyalty_accounts_tier'), 'loyalty_accounts', ['tier'], unique=False, schema='loyalty')
    op.alter_column('loyalty_accounts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='loyalty')
    op.alter_column('loyalty_accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='loyalty')
    op.alter_column('loyalty_accounts', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='loyalty')
    op.alter_column('loyalty_accounts', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='loyalty')
    # ### end Alembic commands ###
