"""tables

Revision ID: 3a0f39f8230c
Revises: 
Create Date: 2025-10-09 13:30:49.894659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a0f39f8230c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=True),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('service_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('scheduled_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='bookings'
    )
    op.create_index(op.f('ix_bookings_bookings_provider_id'), 'bookings', ['provider_id'], unique=False, schema='bookings')
    op.create_index(op.f('ix_bookings_bookings_service_id'), 'bookings', ['service_id'], unique=False, schema='bookings')
    op.create_index(op.f('ix_bookings_bookings_vehicle_id'), 'bookings', ['vehicle_id'], unique=False, schema='bookings')
    op.create_table('service_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=True),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('provider_name', sa.String(length=255), nullable=True),
    sa.Column('provider_contact', sa.JSON(), nullable=True),
    sa.Column('service_id', sa.String(), nullable=True),
    sa.Column('service_name', sa.String(length=255), nullable=True),
    sa.Column('service_items', sa.JSON(), nullable=True),
    sa.Column('mileage_km', sa.Integer(), nullable=True),
    sa.Column('performed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('next_service_km', sa.Integer(), nullable=True),
    sa.Column('next_service_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('served_by', sa.String(length=255), nullable=True),
    sa.Column('mechanic_contact', sa.String(length=255), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('logged_by', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='bookings'
    )
    op.create_index(op.f('ix_bookings_service_logs_provider_id'), 'service_logs', ['provider_id'], unique=False, schema='bookings')
    op.create_index(op.f('ix_bookings_service_logs_service_id'), 'service_logs', ['service_id'], unique=False, schema='bookings')
    op.create_index(op.f('ix_bookings_service_logs_vehicle_id'), 'service_logs', ['vehicle_id'], unique=False, schema='bookings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_service_logs_vehicle_id'), table_name='service_logs', schema='bookings')
    op.drop_index(op.f('ix_bookings_service_logs_service_id'), table_name='service_logs', schema='bookings')
    op.drop_index(op.f('ix_bookings_service_logs_provider_id'), table_name='service_logs', schema='bookings')
    op.drop_table('service_logs', schema='bookings')
    op.drop_index(op.f('ix_bookings_bookings_vehicle_id'), table_name='bookings', schema='bookings')
    op.drop_index(op.f('ix_bookings_bookings_service_id'), table_name='bookings', schema='bookings')
    op.drop_index(op.f('ix_bookings_bookings_provider_id'), table_name='bookings', schema='bookings')
    op.drop_table('bookings', schema='bookings')
    # ### end Alembic commands ###
