"""add booking pricing fields and expense_recorded

Revision ID: f0544d4ff290
Revises: eef2c5704343
Create Date: 2025-10-29 06:27:08.389778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0544d4ff290'
down_revision: Union[str, None] = 'eef2c5704343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('base_price', sa.Integer(), nullable=True), schema='bookings')
    op.add_column('bookings', sa.Column('agreed_price', sa.Integer(), nullable=True), schema='bookings')
    op.add_column('bookings', sa.Column('has_negotiated', sa.Boolean(), nullable=True), schema='bookings')
    op.add_column('bookings', sa.Column('negotiation_notes', sa.String(), nullable=True), schema='bookings')

    # Add NOT NULL boolean with a temporary server default to satisfy existing rows
    op.add_column(
        'bookings',
        sa.Column('expense_recorded', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        schema='bookings'
    )
    # Optionally drop the default so future inserts must set it explicitly
    op.alter_column(
        'bookings',
        'expense_recorded',
        server_default=None,
        existing_type=sa.Boolean(),
        schema='bookings'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'expense_recorded', schema='bookings')
    op.drop_column('bookings', 'negotiation_notes', schema='bookings')
    op.drop_column('bookings', 'has_negotiated', schema='bookings')
    op.drop_column('bookings', 'agreed_price', schema='bookings')
    op.drop_column('bookings', 'base_price', schema='bookings')
    # ### end Alembic commands ###
