"""tables

Revision ID: 5203b7d1e2b4
Revises: c944e8863f46
Create Date: 2025-10-11 11:40:32.525411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5203b7d1e2b4'
down_revision: Union[str, None] = 'c944e8863f46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('make', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('plate', sa.String(), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('yom', sa.Integer(), nullable=True),
    sa.Column('fuel_type', sa.String(), nullable=True),
    sa.Column('transmission', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('guest_owner_name', sa.String(), nullable=True),
    sa.Column('guest_owner_email', sa.String(), nullable=True),
    sa.Column('guest_owner_phone', sa.String(), nullable=True),
    sa.Column('created_by_provider_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='vehicles'
    )
    op.create_index(op.f('ix_vehicles_vehicles_color'), 'vehicles', ['color'], unique=False, schema='vehicles')
    op.create_index(op.f('ix_vehicles_vehicles_fuel_type'), 'vehicles', ['fuel_type'], unique=False, schema='vehicles')
    op.create_index(op.f('ix_vehicles_vehicles_make'), 'vehicles', ['make'], unique=False, schema='vehicles')
    op.create_index(op.f('ix_vehicles_vehicles_model'), 'vehicles', ['model'], unique=False, schema='vehicles')
    op.create_index(op.f('ix_vehicles_vehicles_owner_id'), 'vehicles', ['owner_id'], unique=False, schema='vehicles')
    op.create_index(op.f('ix_vehicles_vehicles_plate'), 'vehicles', ['plate'], unique=True, schema='vehicles')
    op.create_index(op.f('ix_vehicles_vehicles_transmission'), 'vehicles', ['transmission'], unique=False, schema='vehicles')
    op.create_index(op.f('ix_vehicles_vehicles_yom'), 'vehicles', ['yom'], unique=False, schema='vehicles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_vehicles_yom'), table_name='vehicles', schema='vehicles')
    op.drop_index(op.f('ix_vehicles_vehicles_transmission'), table_name='vehicles', schema='vehicles')
    op.drop_index(op.f('ix_vehicles_vehicles_plate'), table_name='vehicles', schema='vehicles')
    op.drop_index(op.f('ix_vehicles_vehicles_owner_id'), table_name='vehicles', schema='vehicles')
    op.drop_index(op.f('ix_vehicles_vehicles_model'), table_name='vehicles', schema='vehicles')
    op.drop_index(op.f('ix_vehicles_vehicles_make'), table_name='vehicles', schema='vehicles')
    op.drop_index(op.f('ix_vehicles_vehicles_fuel_type'), table_name='vehicles', schema='vehicles')
    op.drop_index(op.f('ix_vehicles_vehicles_color'), table_name='vehicles', schema='vehicles')
    op.drop_table('vehicles', schema='vehicles')
    # ### end Alembic commands ###
