"""add_provider_ratings_table

Revision ID: 217e8a26097f
Revises: 3167810ba581
Create Date: 2025-11-04 10:43:03.942984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '217e8a26097f'
down_revision: Union[str, None] = '3167810ba581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: provider_service_view is a database view, not a table, so it's excluded
    op.create_table('provider_ratings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['service_providers.providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='service_providers'
    )
    op.create_index(op.f('ix_service_providers_provider_ratings_booking_id'), 'provider_ratings', ['booking_id'], unique=False, schema='service_providers')
    op.create_index(op.f('ix_service_providers_provider_ratings_provider_id'), 'provider_ratings', ['provider_id'], unique=False, schema='service_providers')
    op.create_index(op.f('ix_service_providers_provider_ratings_user_id'), 'provider_ratings', ['user_id'], unique=False, schema='service_providers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_providers_provider_ratings_user_id'), table_name='provider_ratings', schema='service_providers')
    op.drop_index(op.f('ix_service_providers_provider_ratings_provider_id'), table_name='provider_ratings', schema='service_providers')
    op.drop_index(op.f('ix_service_providers_provider_ratings_booking_id'), table_name='provider_ratings', schema='service_providers')
    op.drop_table('provider_ratings', schema='service_providers')
    # ### end Alembic commands ###
