"""tables

Revision ID: 954839468274
Revises: 
Create Date: 2025-10-11 09:13:49.709115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '954839468274'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='service_providers'
    )
    op.create_table('provider_service_view',
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('provider_name', sa.String(), nullable=True),
    sa.Column('provider_category_id', sa.Integer(), nullable=True),
    sa.Column('provider_description', sa.Text(), nullable=True),
    sa.Column('provider_contact_info', sa.JSON(), nullable=True),
    sa.Column('provider_location', sa.JSON(), nullable=True),
    sa.Column('provider_rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('provider_is_registered', sa.Boolean(), nullable=True),
    sa.Column('provider_created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('provider_service_id', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('booking_required', sa.Boolean(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('service_id', sa.String(), nullable=True),
    sa.Column('service_name', sa.String(), nullable=True),
    sa.Column('service_category_id', sa.Integer(), nullable=True),
    schema='service_providers'
    )
    op.create_table('service_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='service_providers'
    )
    op.create_table('providers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_info', sa.JSON(), nullable=True),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('is_registered', sa.Boolean(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['service_providers.provider_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='service_providers'
    )
    op.create_table('services',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.JSON(), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['service_providers.service_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='service_providers'
    )
    op.create_table('provider_services',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('service_id', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('price', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('booking_required', sa.Boolean(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['service_providers.providers.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service_providers.services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='service_providers'
    )
    op.create_table('service_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['service_providers.providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='service_providers'
    )
    op.create_table('service_template_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('service_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['service_providers.services.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['service_providers.service_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='service_providers'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_template_items', schema='service_providers')
    op.drop_table('service_templates', schema='service_providers')
    op.drop_table('provider_services', schema='service_providers')
    op.drop_table('services', schema='service_providers')
    op.drop_table('providers', schema='service_providers')
    op.drop_table('service_categories', schema='service_providers')
    op.drop_table('provider_service_view', schema='service_providers')
    op.drop_table('provider_categories', schema='service_providers')
    # ### end Alembic commands ###
