"""create users table

Revision ID: 1cefd66d51c1
Revises: d5d12c2ca874
Create Date: 2025-09-19 14:23:12.027463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1cefd66d51c1'
down_revision: Union[str, Sequence[str], None] = 'd5d12c2ca874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tbl_auths_auth_provider'), table_name='tbl_auths', schema='users')
    op.drop_index(op.f('ix_users_tbl_auths_email'), table_name='tbl_auths', schema='users')
    op.drop_index(op.f('ix_users_tbl_auths_id'), table_name='tbl_auths', schema='users')
    op.drop_index(op.f('ix_users_tbl_auths_name'), table_name='tbl_auths', schema='users')
    op.drop_index(op.f('ix_users_tbl_auths_phone'), table_name='tbl_auths', schema='users')
    op.drop_index(op.f('ix_users_tbl_auths_role'), table_name='tbl_auths', schema='users')
    op.drop_table('tbl_auths', schema='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_auths',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('passcode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('auth_provider', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('verified', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tbl_auths_pkey')),
    schema='users'
    )
    op.create_index(op.f('ix_users_tbl_auths_role'), 'tbl_auths', ['role'], unique=False, schema='users')
    op.create_index(op.f('ix_users_tbl_auths_phone'), 'tbl_auths', ['phone'], unique=False, schema='users')
    op.create_index(op.f('ix_users_tbl_auths_name'), 'tbl_auths', ['name'], unique=False, schema='users')
    op.create_index(op.f('ix_users_tbl_auths_id'), 'tbl_auths', ['id'], unique=False, schema='users')
    op.create_index(op.f('ix_users_tbl_auths_email'), 'tbl_auths', ['email'], unique=True, schema='users')
    op.create_index(op.f('ix_users_tbl_auths_auth_provider'), 'tbl_auths', ['auth_provider'], unique=False, schema='users')
    # ### end Alembic commands ###
