"""tables initialization

Revision ID: 6990efd8d81d
Revises: 
Create Date: 2025-10-21 19:44:20.164161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6990efd8d81d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_auth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('auth_provider', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('is_guest', sa.Boolean(), nullable=True),
    sa.Column('created_by_provider_id', sa.String(), nullable=True),
    sa.Column('fcm_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_index(op.f('ix_users_tbl_auth_auth_provider'), 'tbl_auth', ['auth_provider'], unique=False, schema='users')
    op.create_index(op.f('ix_users_tbl_auth_email'), 'tbl_auth', ['email'], unique=True, schema='users')
    op.create_index(op.f('ix_users_tbl_auth_id'), 'tbl_auth', ['id'], unique=False, schema='users')
    op.create_index(op.f('ix_users_tbl_auth_name'), 'tbl_auth', ['name'], unique=False, schema='users')
    op.create_index(op.f('ix_users_tbl_auth_phone'), 'tbl_auth', ['phone'], unique=False, schema='users')
    op.create_table('tbl_otp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_index(op.f('ix_users_tbl_otp_email'), 'tbl_otp', ['email'], unique=False, schema='users')
    op.create_index(op.f('ix_users_tbl_otp_id'), 'tbl_otp', ['id'], unique=False, schema='users')
    op.create_table('tbl_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_index(op.f('ix_users_tbl_roles_name'), 'tbl_roles', ['name'], unique=False, schema='users')
    op.create_table('provider_user_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.tbl_auth.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_table('tbl_auth_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.tbl_auth.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_auth_roles', schema='users')
    op.drop_table('provider_user_links', schema='users')
    op.drop_index(op.f('ix_users_tbl_roles_name'), table_name='tbl_roles', schema='users')
    op.drop_table('tbl_roles', schema='users')
    op.drop_index(op.f('ix_users_tbl_otp_id'), table_name='tbl_otp', schema='users')
    op.drop_index(op.f('ix_users_tbl_otp_email'), table_name='tbl_otp', schema='users')
    op.drop_table('tbl_otp', schema='users')
    op.drop_index(op.f('ix_users_tbl_auth_phone'), table_name='tbl_auth', schema='users')
    op.drop_index(op.f('ix_users_tbl_auth_name'), table_name='tbl_auth', schema='users')
    op.drop_index(op.f('ix_users_tbl_auth_id'), table_name='tbl_auth', schema='users')
    op.drop_index(op.f('ix_users_tbl_auth_email'), table_name='tbl_auth', schema='users')
    op.drop_index(op.f('ix_users_tbl_auth_auth_provider'), table_name='tbl_auth', schema='users')
    op.drop_table('tbl_auth', schema='users')
    # ### end Alembic commands ###
