"""create users table

Revision ID: 7fcb2c4761a7
Revises: fd649b250869
Create Date: 2025-09-20 15:32:48.249038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fcb2c4761a7'
down_revision: Union[str, Sequence[str], None] = 'fd649b250869'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_auth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('passcode', sa.String(), nullable=True),
    sa.Column('auth_provider', sa.String(), nullable=True),
    sa.Column('verified', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_index(op.f('ix_users_tbl_auth_auth_provider'), 'tbl_auth', ['auth_provider'], unique=False, schema='users')
    op.create_index(op.f('ix_users_tbl_auth_email'), 'tbl_auth', ['email'], unique=True, schema='users')
    op.create_index(op.f('ix_users_tbl_auth_id'), 'tbl_auth', ['id'], unique=False, schema='users')
    op.create_index(op.f('ix_users_tbl_auth_name'), 'tbl_auth', ['name'], unique=False, schema='users')
    op.create_index(op.f('ix_users_tbl_auth_phone'), 'tbl_auth', ['phone'], unique=False, schema='users')
    op.create_index(op.f('ix_users_tbl_auth_role'), 'tbl_auth', ['role'], unique=False, schema='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tbl_auth_role'), table_name='tbl_auth', schema='users')
    op.drop_index(op.f('ix_users_tbl_auth_phone'), table_name='tbl_auth', schema='users')
    op.drop_index(op.f('ix_users_tbl_auth_name'), table_name='tbl_auth', schema='users')
    op.drop_index(op.f('ix_users_tbl_auth_id'), table_name='tbl_auth', schema='users')
    op.drop_index(op.f('ix_users_tbl_auth_email'), table_name='tbl_auth', schema='users')
    op.drop_index(op.f('ix_users_tbl_auth_auth_provider'), table_name='tbl_auth', schema='users')
    op.drop_table('tbl_auth', schema='users')
    # ### end Alembic commands ###
