"""Create users table

Revision ID: 80d03864e7f4
Revises: c11683ddc28e
Create Date: 2025-09-29 11:11:28.540169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80d03864e7f4'
down_revision: Union[str, Sequence[str], None] = 'c11683ddc28e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_index(op.f('ix_users_tbl_roles_name'), 'tbl_roles', ['name'], unique=False, schema='users')
    op.create_table('tbl_auth_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.tbl_auth.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.drop_index(op.f('ix_users_tbl_auth_role'), table_name='tbl_auth', schema='users')
    op.drop_column('tbl_auth', 'role', schema='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_auth', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True), schema='users')
    op.create_index(op.f('ix_users_tbl_auth_role'), 'tbl_auth', ['role'], unique=False, schema='users')
    op.drop_table('tbl_auth_roles', schema='users')
    op.drop_index(op.f('ix_users_tbl_roles_name'), table_name='tbl_roles', schema='users')
    op.drop_table('tbl_roles', schema='users')
    # ### end Alembic commands ###
