"""tables initialization

Revision ID: 37f1fda05547
Revises: 
Create Date: 2025-10-21 19:45:17.033111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37f1fda05547'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_preferences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.Enum('INSURANCE_EXPIRY', 'SERVICE_DUE', 'PROMOTIONAL', 'MAINTENANCE_REMINDER', 'CLAIM_UPDATE', 'PAYMENT_REMINDER', name='alerttype'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('quiet_hours_start', sa.String(), nullable=True),
    sa.Column('quiet_hours_end', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('min_priority', sa.Integer(), nullable=True),
    sa.Column('batch_alerts', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='alerts'
    )
    op.create_index(op.f('ix_alerts_alert_preferences_alert_type'), 'alert_preferences', ['alert_type'], unique=False, schema='alerts')
    op.create_index(op.f('ix_alerts_alert_preferences_user_id'), 'alert_preferences', ['user_id'], unique=False, schema='alerts')
    op.create_table('alert_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('alert_type', sa.Enum('INSURANCE_EXPIRY', 'SERVICE_DUE', 'PROMOTIONAL', 'MAINTENANCE_REMINDER', 'CLAIM_UPDATE', 'PAYMENT_REMINDER', name='alerttype'), nullable=False),
    sa.Column('trigger_conditions', sa.JSON(), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('title_template', sa.String(length=255), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('schedule_expression', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='alerts'
    )
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('INSURANCE_EXPIRY', 'SERVICE_DUE', 'PROMOTIONAL', 'MAINTENANCE_REMINDER', 'CLAIM_UPDATE', 'PAYMENT_REMINDER', name='alerttype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.String(), nullable=True),
    sa.Column('policy_id', sa.String(), nullable=True),
    sa.Column('booking_id', sa.String(), nullable=True),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'FAILED', 'CANCELLED', name='alertstatus'), nullable=True),
    sa.Column('scheduled_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('sent_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('action_url', sa.String(), nullable=True),
    sa.Column('action_text', sa.String(), nullable=True),
    sa.Column('alert_metadata', sa.JSON(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='alerts'
    )
    op.create_index(op.f('ix_alerts_alerts_booking_id'), 'alerts', ['booking_id'], unique=False, schema='alerts')
    op.create_index(op.f('ix_alerts_alerts_policy_id'), 'alerts', ['policy_id'], unique=False, schema='alerts')
    op.create_index(op.f('ix_alerts_alerts_provider_id'), 'alerts', ['provider_id'], unique=False, schema='alerts')
    op.create_index(op.f('ix_alerts_alerts_status'), 'alerts', ['status'], unique=False, schema='alerts')
    op.create_index(op.f('ix_alerts_alerts_type'), 'alerts', ['type'], unique=False, schema='alerts')
    op.create_index(op.f('ix_alerts_alerts_user_id'), 'alerts', ['user_id'], unique=False, schema='alerts')
    op.create_index(op.f('ix_alerts_alerts_vehicle_id'), 'alerts', ['vehicle_id'], unique=False, schema='alerts')
    op.create_table('notification_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('alert_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('IN_APP', 'PUSH', 'SMS', 'EMAIL', 'WHATSAPP', name='alertchannel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'FAILED', 'CANCELLED', name='alertstatus'), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('external_response', sa.JSON(), nullable=True),
    sa.Column('sent_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('delivered_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.alerts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='alerts'
    )
    op.create_index(op.f('ix_alerts_notification_logs_alert_id'), 'notification_logs', ['alert_id'], unique=False, schema='alerts')
    op.create_index(op.f('ix_alerts_notification_logs_user_id'), 'notification_logs', ['user_id'], unique=False, schema='alerts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_notification_logs_user_id'), table_name='notification_logs', schema='alerts')
    op.drop_index(op.f('ix_alerts_notification_logs_alert_id'), table_name='notification_logs', schema='alerts')
    op.drop_table('notification_logs', schema='alerts')
    op.drop_index(op.f('ix_alerts_alerts_vehicle_id'), table_name='alerts', schema='alerts')
    op.drop_index(op.f('ix_alerts_alerts_user_id'), table_name='alerts', schema='alerts')
    op.drop_index(op.f('ix_alerts_alerts_type'), table_name='alerts', schema='alerts')
    op.drop_index(op.f('ix_alerts_alerts_status'), table_name='alerts', schema='alerts')
    op.drop_index(op.f('ix_alerts_alerts_provider_id'), table_name='alerts', schema='alerts')
    op.drop_index(op.f('ix_alerts_alerts_policy_id'), table_name='alerts', schema='alerts')
    op.drop_index(op.f('ix_alerts_alerts_booking_id'), table_name='alerts', schema='alerts')
    op.drop_table('alerts', schema='alerts')
    op.drop_table('alert_rules', schema='alerts')
    op.drop_index(op.f('ix_alerts_alert_preferences_user_id'), table_name='alert_preferences', schema='alerts')
    op.drop_index(op.f('ix_alerts_alert_preferences_alert_type'), table_name='alert_preferences', schema='alerts')
    op.drop_table('alert_preferences', schema='alerts')
    # ### end Alembic commands ###
