"""Create policy table

Revision ID: 1bfec55aef10
Revises: 
Create Date: 2025-09-29 14:48:11.143216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bfec55aef10'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('vehicle_id', sa.String(), nullable=True),
    sa.Column('insurance_type', sa.String(), nullable=True),
    sa.Column('insurer_id', sa.String(), nullable=True),
    sa.Column('commencement_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('expiry_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='insurance'
    )
    op.create_index(op.f('ix_insurance_insurance_policies_insurance_type'), 'insurance_policies', ['insurance_type'], unique=False, schema='insurance')
    op.create_index(op.f('ix_insurance_insurance_policies_insurer_id'), 'insurance_policies', ['insurer_id'], unique=False, schema='insurance')
    op.create_index(op.f('ix_insurance_insurance_policies_owner_id'), 'insurance_policies', ['owner_id'], unique=False, schema='insurance')
    op.create_index(op.f('ix_insurance_insurance_policies_vehicle_id'), 'insurance_policies', ['vehicle_id'], unique=False, schema='insurance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insurance_insurance_policies_vehicle_id'), table_name='insurance_policies', schema='insurance')
    op.drop_index(op.f('ix_insurance_insurance_policies_owner_id'), table_name='insurance_policies', schema='insurance')
    op.drop_index(op.f('ix_insurance_insurance_policies_insurer_id'), table_name='insurance_policies', schema='insurance')
    op.drop_index(op.f('ix_insurance_insurance_policies_insurance_type'), table_name='insurance_policies', schema='insurance')
    op.drop_table('insurance_policies', schema='insurance')
    # ### end Alembic commands ###
