"""tables initialization

Revision ID: 8d9be6edc7e5
Revises: 
Create Date: 2025-10-21 19:45:05.643790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d9be6edc7e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_partners',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('api_endpoint', sa.String(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('webhook_url', sa.String(), nullable=True),
    sa.Column('supports_quotes', sa.Boolean(), nullable=True),
    sa.Column('supports_claims', sa.Boolean(), nullable=True),
    sa.Column('supports_data_feeds', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('commission_rate', sa.Integer(), nullable=True),
    sa.Column('contact_info', sa.JSON(), nullable=True),
    sa.Column('supported_coverage_types', sa.JSON(), nullable=True),
    sa.Column('customer_rating', sa.Integer(), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('claims_processing_time', sa.String(), nullable=True),
    sa.Column('policy_validity_period', sa.String(), nullable=True),
    sa.Column('special_features', sa.JSON(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('established_year', sa.Integer(), nullable=True),
    sa.Column('market_share', sa.String(), nullable=True),
    sa.Column('awards', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='insurance'
    )
    op.create_index(op.f('ix_insurance_insurance_partners_code'), 'insurance_partners', ['code'], unique=True, schema='insurance')
    op.create_index(op.f('ix_insurance_insurance_partners_name'), 'insurance_partners', ['name'], unique=False, schema='insurance')
    op.create_table('insurance_policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.String(), nullable=True),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('insurance_type', sa.String(), nullable=True),
    sa.Column('commencement_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('expiry_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('premium_amount', sa.Integer(), nullable=True),
    sa.Column('coverage_details', sa.JSON(), nullable=True),
    sa.Column('deductible_amount', sa.Integer(), nullable=True),
    sa.Column('policy_number', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('renewal_reminder_sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='insurance'
    )
    op.create_index(op.f('ix_insurance_insurance_policies_insurance_type'), 'insurance_policies', ['insurance_type'], unique=False, schema='insurance')
    op.create_index(op.f('ix_insurance_insurance_policies_owner_id'), 'insurance_policies', ['owner_id'], unique=False, schema='insurance')
    op.create_index(op.f('ix_insurance_insurance_policies_policy_number'), 'insurance_policies', ['policy_number'], unique=True, schema='insurance')
    op.create_index(op.f('ix_insurance_insurance_policies_provider_id'), 'insurance_policies', ['provider_id'], unique=False, schema='insurance')
    op.create_index(op.f('ix_insurance_insurance_policies_vehicle_id'), 'insurance_policies', ['vehicle_id'], unique=False, schema='insurance')
    op.create_table('risk_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_risk_score', sa.Integer(), nullable=True),
    sa.Column('driver_risk_score', sa.Integer(), nullable=True),
    sa.Column('combined_risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('scoring_algorithm_version', sa.String(), nullable=True),
    sa.Column('data_points_used', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='insurance'
    )
    op.create_index(op.f('ix_insurance_risk_scores_user_id'), 'risk_scores', ['user_id'], unique=False, schema='insurance')
    op.create_index(op.f('ix_insurance_risk_scores_vehicle_id'), 'risk_scores', ['vehicle_id'], unique=False, schema='insurance')
    op.create_table('data_feed_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('partner_id', sa.String(), nullable=True),
    sa.Column('vehicle_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('feed_type', sa.String(), nullable=True),
    sa.Column('data_payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('sent_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['insurance.insurance_partners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='insurance'
    )
    op.create_index(op.f('ix_insurance_data_feed_logs_feed_type'), 'data_feed_logs', ['feed_type'], unique=False, schema='insurance')
    op.create_index(op.f('ix_insurance_data_feed_logs_partner_id'), 'data_feed_logs', ['partner_id'], unique=False, schema='insurance')
    op.create_index(op.f('ix_insurance_data_feed_logs_user_id'), 'data_feed_logs', ['user_id'], unique=False, schema='insurance')
    op.create_index(op.f('ix_insurance_data_feed_logs_vehicle_id'), 'data_feed_logs', ['vehicle_id'], unique=False, schema='insurance')
    op.create_table('insurance_claims',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('policy_id', sa.String(), nullable=True),
    sa.Column('vehicle_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('claim_type', sa.String(), nullable=True),
    sa.Column('incident_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_cost', sa.Integer(), nullable=True),
    sa.Column('actual_cost', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('claim_number', sa.String(), nullable=True),
    sa.Column('evidence_files', sa.JSON(), nullable=True),
    sa.Column('repair_quotes', sa.JSON(), nullable=True),
    sa.Column('assigned_adjuster', sa.String(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('approved_amount', sa.Integer(), nullable=True),
    sa.Column('payment_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['insurance.insurance_policies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='insurance'
    )
    op.create_index(op.f('ix_insurance_insurance_claims_claim_number'), 'insurance_claims', ['claim_number'], unique=True, schema='insurance')
    op.create_index(op.f('ix_insurance_insurance_claims_claim_type'), 'insurance_claims', ['claim_type'], unique=False, schema='insurance')
    op.create_index(op.f('ix_insurance_insurance_claims_policy_id'), 'insurance_claims', ['policy_id'], unique=False, schema='insurance')
    op.create_index(op.f('ix_insurance_insurance_claims_user_id'), 'insurance_claims', ['user_id'], unique=False, schema='insurance')
    op.create_index(op.f('ix_insurance_insurance_claims_vehicle_id'), 'insurance_claims', ['vehicle_id'], unique=False, schema='insurance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insurance_insurance_claims_vehicle_id'), table_name='insurance_claims', schema='insurance')
    op.drop_index(op.f('ix_insurance_insurance_claims_user_id'), table_name='insurance_claims', schema='insurance')
    op.drop_index(op.f('ix_insurance_insurance_claims_policy_id'), table_name='insurance_claims', schema='insurance')
    op.drop_index(op.f('ix_insurance_insurance_claims_claim_type'), table_name='insurance_claims', schema='insurance')
    op.drop_index(op.f('ix_insurance_insurance_claims_claim_number'), table_name='insurance_claims', schema='insurance')
    op.drop_table('insurance_claims', schema='insurance')
    op.drop_index(op.f('ix_insurance_data_feed_logs_vehicle_id'), table_name='data_feed_logs', schema='insurance')
    op.drop_index(op.f('ix_insurance_data_feed_logs_user_id'), table_name='data_feed_logs', schema='insurance')
    op.drop_index(op.f('ix_insurance_data_feed_logs_partner_id'), table_name='data_feed_logs', schema='insurance')
    op.drop_index(op.f('ix_insurance_data_feed_logs_feed_type'), table_name='data_feed_logs', schema='insurance')
    op.drop_table('data_feed_logs', schema='insurance')
    op.drop_index(op.f('ix_insurance_risk_scores_vehicle_id'), table_name='risk_scores', schema='insurance')
    op.drop_index(op.f('ix_insurance_risk_scores_user_id'), table_name='risk_scores', schema='insurance')
    op.drop_table('risk_scores', schema='insurance')
    op.drop_index(op.f('ix_insurance_insurance_policies_vehicle_id'), table_name='insurance_policies', schema='insurance')
    op.drop_index(op.f('ix_insurance_insurance_policies_provider_id'), table_name='insurance_policies', schema='insurance')
    op.drop_index(op.f('ix_insurance_insurance_policies_policy_number'), table_name='insurance_policies', schema='insurance')
    op.drop_index(op.f('ix_insurance_insurance_policies_owner_id'), table_name='insurance_policies', schema='insurance')
    op.drop_index(op.f('ix_insurance_insurance_policies_insurance_type'), table_name='insurance_policies', schema='insurance')
    op.drop_table('insurance_policies', schema='insurance')
    op.drop_index(op.f('ix_insurance_insurance_partners_name'), table_name='insurance_partners', schema='insurance')
    op.drop_index(op.f('ix_insurance_insurance_partners_code'), table_name='insurance_partners', schema='insurance')
    op.drop_table('insurance_partners', schema='insurance')
    # ### end Alembic commands ###
