"""tables

Revision ID: b9f7c17de47a
Revises: bbe86b6b4387
Create Date: 2025-10-11 11:39:22.308234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9f7c17de47a'
down_revision: Union[str, None] = 'bbe86b6b4387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.String(), nullable=True),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('insurance_type', sa.String(), nullable=True),
    sa.Column('commencement_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('expiry_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='insurance'
    )
    op.create_index(op.f('ix_insurance_insurance_policies_insurance_type'), 'insurance_policies', ['insurance_type'], unique=False, schema='insurance')
    op.create_index(op.f('ix_insurance_insurance_policies_owner_id'), 'insurance_policies', ['owner_id'], unique=False, schema='insurance')
    op.create_index(op.f('ix_insurance_insurance_policies_provider_id'), 'insurance_policies', ['provider_id'], unique=False, schema='insurance')
    op.create_index(op.f('ix_insurance_insurance_policies_vehicle_id'), 'insurance_policies', ['vehicle_id'], unique=False, schema='insurance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insurance_insurance_policies_vehicle_id'), table_name='insurance_policies', schema='insurance')
    op.drop_index(op.f('ix_insurance_insurance_policies_provider_id'), table_name='insurance_policies', schema='insurance')
    op.drop_index(op.f('ix_insurance_insurance_policies_owner_id'), table_name='insurance_policies', schema='insurance')
    op.drop_index(op.f('ix_insurance_insurance_policies_insurance_type'), table_name='insurance_policies', schema='insurance')
    op.drop_table('insurance_policies', schema='insurance')
    # ### end Alembic commands ###
