"""initial tables

Revision ID: 2f16032effb3
Revises: 
Create Date: 2025-10-21 20:18:57.176298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f16032effb3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='social'
    )
    op.create_index('idx_follows_follower', 'follows', ['follower_id', 'created_at'], unique=False, schema='social')
    op.create_index('idx_follows_following', 'follows', ['following_id', 'created_at'], unique=False, schema='social')
    op.create_index('idx_follows_unique', 'follows', ['follower_id', 'following_id'], unique=True, schema='social')
    op.create_index(op.f('ix_social_follows_follower_id'), 'follows', ['follower_id'], unique=False, schema='social')
    op.create_index(op.f('ix_social_follows_following_id'), 'follows', ['following_id'], unique=False, schema='social')
    op.create_table('hashtags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('posts_count', sa.Integer(), nullable=True),
    sa.Column('last_used', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='social'
    )
    op.create_index('idx_hashtags_last_used', 'hashtags', ['last_used'], unique=False, schema='social')
    op.create_index('idx_hashtags_posts_count', 'hashtags', ['posts_count'], unique=False, schema='social')
    op.create_index(op.f('ix_social_hashtags_name'), 'hashtags', ['name'], unique=True, schema='social')
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_user_id', sa.Integer(), nullable=True),
    sa.Column('related_post_id', sa.String(), nullable=True),
    sa.Column('related_comment_id', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('read_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='social'
    )
    op.create_index('idx_notifications_type', 'notifications', ['type', 'created_at'], unique=False, schema='social')
    op.create_index('idx_notifications_user_unread', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False, schema='social')
    op.create_index(op.f('ix_social_notifications_related_comment_id'), 'notifications', ['related_comment_id'], unique=False, schema='social')
    op.create_index(op.f('ix_social_notifications_related_post_id'), 'notifications', ['related_post_id'], unique=False, schema='social')
    op.create_index(op.f('ix_social_notifications_related_user_id'), 'notifications', ['related_user_id'], unique=False, schema='social')
    op.create_index(op.f('ix_social_notifications_user_id'), 'notifications', ['user_id'], unique=False, schema='social')
    op.create_table('posts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('media_urls', sa.JSON(), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('is_sponsored', sa.Boolean(), nullable=True),
    sa.Column('sponsored_by', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='social'
    )
    op.create_index('idx_posts_provider_created', 'posts', ['provider_id', 'created_at'], unique=False, schema='social')
    op.create_index('idx_posts_sponsored_created', 'posts', ['is_sponsored', 'created_at'], unique=False, schema='social')
    op.create_index('idx_posts_status_created', 'posts', ['status', 'created_at'], unique=False, schema='social')
    op.create_index('idx_posts_user_created', 'posts', ['user_id', 'created_at'], unique=False, schema='social')
    op.create_index(op.f('ix_social_posts_provider_id'), 'posts', ['provider_id'], unique=False, schema='social')
    op.create_index(op.f('ix_social_posts_user_id'), 'posts', ['user_id'], unique=False, schema='social')
    op.create_table('stories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('media_url', sa.String(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='social'
    )
    op.create_index('idx_stories_expires', 'stories', ['expires_at'], unique=False, schema='social')
    op.create_index('idx_stories_user_created', 'stories', ['user_id', 'created_at'], unique=False, schema='social')
    op.create_index(op.f('ix_social_stories_provider_id'), 'stories', ['provider_id'], unique=False, schema='social')
    op.create_index(op.f('ix_social_stories_user_id'), 'stories', ['user_id'], unique=False, schema='social')
    op.create_table('user_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('posts_count', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_provider', sa.Boolean(), nullable=True),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('allow_messages', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='social'
    )
    op.create_index('idx_profiles_provider', 'user_profiles', ['provider_id'], unique=False, schema='social')
    op.create_index('idx_profiles_username', 'user_profiles', ['username'], unique=False, schema='social')
    op.create_index('idx_profiles_verified', 'user_profiles', ['is_verified'], unique=False, schema='social')
    op.create_index(op.f('ix_social_user_profiles_provider_id'), 'user_profiles', ['provider_id'], unique=False, schema='social')
    op.create_index(op.f('ix_social_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True, schema='social')
    op.create_index(op.f('ix_social_user_profiles_username'), 'user_profiles', ['username'], unique=True, schema='social')
    op.create_table('comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['social.comments.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['social.posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='social'
    )
    op.create_index('idx_comments_parent', 'comments', ['parent_id'], unique=False, schema='social')
    op.create_index('idx_comments_post_created', 'comments', ['post_id', 'created_at'], unique=False, schema='social')
    op.create_index('idx_comments_user_created', 'comments', ['user_id', 'created_at'], unique=False, schema='social')
    op.create_index(op.f('ix_social_comments_post_id'), 'comments', ['post_id'], unique=False, schema='social')
    op.create_index(op.f('ix_social_comments_user_id'), 'comments', ['user_id'], unique=False, schema='social')
    op.create_table('post_analytics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['social.posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='social'
    )
    op.create_index('idx_analytics_likes', 'post_analytics', ['likes'], unique=False, schema='social')
    op.create_index('idx_analytics_updated', 'post_analytics', ['updated_at'], unique=False, schema='social')
    op.create_index('idx_analytics_views', 'post_analytics', ['views'], unique=False, schema='social')
    op.create_index(op.f('ix_social_post_analytics_post_id'), 'post_analytics', ['post_id'], unique=True, schema='social')
    op.create_table('shares',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('shared_to', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['social.posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='social'
    )
    op.create_index('idx_shares_post_created', 'shares', ['post_id', 'created_at'], unique=False, schema='social')
    op.create_index('idx_shares_user_created', 'shares', ['user_id', 'created_at'], unique=False, schema='social')
    op.create_index(op.f('ix_social_shares_post_id'), 'shares', ['post_id'], unique=False, schema='social')
    op.create_index(op.f('ix_social_shares_user_id'), 'shares', ['user_id'], unique=False, schema='social')
    op.create_table('story_views',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['social.stories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='social'
    )
    op.create_index('idx_story_views_story', 'story_views', ['story_id', 'viewed_at'], unique=False, schema='social')
    op.create_index('idx_story_views_unique', 'story_views', ['story_id', 'user_id'], unique=True, schema='social')
    op.create_index(op.f('ix_social_story_views_story_id'), 'story_views', ['story_id'], unique=False, schema='social')
    op.create_index(op.f('ix_social_story_views_user_id'), 'story_views', ['user_id'], unique=False, schema='social')
    op.create_table('likes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=True),
    sa.Column('comment_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['social.comments.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['social.posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='social'
    )
    op.create_index('idx_likes_user_comment', 'likes', ['user_id', 'comment_id'], unique=True, schema='social')
    op.create_index('idx_likes_user_post', 'likes', ['user_id', 'post_id'], unique=True, schema='social')
    op.create_index(op.f('ix_social_likes_comment_id'), 'likes', ['comment_id'], unique=False, schema='social')
    op.create_index(op.f('ix_social_likes_post_id'), 'likes', ['post_id'], unique=False, schema='social')
    op.create_index(op.f('ix_social_likes_user_id'), 'likes', ['user_id'], unique=False, schema='social')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_likes_user_id'), table_name='likes', schema='social')
    op.drop_index(op.f('ix_social_likes_post_id'), table_name='likes', schema='social')
    op.drop_index(op.f('ix_social_likes_comment_id'), table_name='likes', schema='social')
    op.drop_index('idx_likes_user_post', table_name='likes', schema='social')
    op.drop_index('idx_likes_user_comment', table_name='likes', schema='social')
    op.drop_table('likes', schema='social')
    op.drop_index(op.f('ix_social_story_views_user_id'), table_name='story_views', schema='social')
    op.drop_index(op.f('ix_social_story_views_story_id'), table_name='story_views', schema='social')
    op.drop_index('idx_story_views_unique', table_name='story_views', schema='social')
    op.drop_index('idx_story_views_story', table_name='story_views', schema='social')
    op.drop_table('story_views', schema='social')
    op.drop_index(op.f('ix_social_shares_user_id'), table_name='shares', schema='social')
    op.drop_index(op.f('ix_social_shares_post_id'), table_name='shares', schema='social')
    op.drop_index('idx_shares_user_created', table_name='shares', schema='social')
    op.drop_index('idx_shares_post_created', table_name='shares', schema='social')
    op.drop_table('shares', schema='social')
    op.drop_index(op.f('ix_social_post_analytics_post_id'), table_name='post_analytics', schema='social')
    op.drop_index('idx_analytics_views', table_name='post_analytics', schema='social')
    op.drop_index('idx_analytics_updated', table_name='post_analytics', schema='social')
    op.drop_index('idx_analytics_likes', table_name='post_analytics', schema='social')
    op.drop_table('post_analytics', schema='social')
    op.drop_index(op.f('ix_social_comments_user_id'), table_name='comments', schema='social')
    op.drop_index(op.f('ix_social_comments_post_id'), table_name='comments', schema='social')
    op.drop_index('idx_comments_user_created', table_name='comments', schema='social')
    op.drop_index('idx_comments_post_created', table_name='comments', schema='social')
    op.drop_index('idx_comments_parent', table_name='comments', schema='social')
    op.drop_table('comments', schema='social')
    op.drop_index(op.f('ix_social_user_profiles_username'), table_name='user_profiles', schema='social')
    op.drop_index(op.f('ix_social_user_profiles_user_id'), table_name='user_profiles', schema='social')
    op.drop_index(op.f('ix_social_user_profiles_provider_id'), table_name='user_profiles', schema='social')
    op.drop_index('idx_profiles_verified', table_name='user_profiles', schema='social')
    op.drop_index('idx_profiles_username', table_name='user_profiles', schema='social')
    op.drop_index('idx_profiles_provider', table_name='user_profiles', schema='social')
    op.drop_table('user_profiles', schema='social')
    op.drop_index(op.f('ix_social_stories_user_id'), table_name='stories', schema='social')
    op.drop_index(op.f('ix_social_stories_provider_id'), table_name='stories', schema='social')
    op.drop_index('idx_stories_user_created', table_name='stories', schema='social')
    op.drop_index('idx_stories_expires', table_name='stories', schema='social')
    op.drop_table('stories', schema='social')
    op.drop_index(op.f('ix_social_posts_user_id'), table_name='posts', schema='social')
    op.drop_index(op.f('ix_social_posts_provider_id'), table_name='posts', schema='social')
    op.drop_index('idx_posts_user_created', table_name='posts', schema='social')
    op.drop_index('idx_posts_status_created', table_name='posts', schema='social')
    op.drop_index('idx_posts_sponsored_created', table_name='posts', schema='social')
    op.drop_index('idx_posts_provider_created', table_name='posts', schema='social')
    op.drop_table('posts', schema='social')
    op.drop_index(op.f('ix_social_notifications_user_id'), table_name='notifications', schema='social')
    op.drop_index(op.f('ix_social_notifications_related_user_id'), table_name='notifications', schema='social')
    op.drop_index(op.f('ix_social_notifications_related_post_id'), table_name='notifications', schema='social')
    op.drop_index(op.f('ix_social_notifications_related_comment_id'), table_name='notifications', schema='social')
    op.drop_index('idx_notifications_user_unread', table_name='notifications', schema='social')
    op.drop_index('idx_notifications_type', table_name='notifications', schema='social')
    op.drop_table('notifications', schema='social')
    op.drop_index(op.f('ix_social_hashtags_name'), table_name='hashtags', schema='social')
    op.drop_index('idx_hashtags_posts_count', table_name='hashtags', schema='social')
    op.drop_index('idx_hashtags_last_used', table_name='hashtags', schema='social')
    op.drop_table('hashtags', schema='social')
    op.drop_index(op.f('ix_social_follows_following_id'), table_name='follows', schema='social')
    op.drop_index(op.f('ix_social_follows_follower_id'), table_name='follows', schema='social')
    op.drop_index('idx_follows_unique', table_name='follows', schema='social')
    op.drop_index('idx_follows_following', table_name='follows', schema='social')
    op.drop_index('idx_follows_follower', table_name='follows', schema='social')
    op.drop_table('follows', schema='social')
    # ### end Alembic commands ###
